### PR TITLE
Create 2016-04-13-working-with-c-unions-in-rust-ffi.md

### PR DESCRIPTION
**Pull request by DarkEld3r**
This change is [Reviewable](https://reviewable.io/reviews/rurust/rustycrate.ru/101)

### CODE REVIEW

**Comment by mkpankov** [comment]
Спасибо за PR! Посмотрю его следующим.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-:-KFIzc58MaBbyCYAkrZz:-398136256)*

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 15 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT4QPL58r008ub-fH_:-KFT4QPL58r008ub-fHa:-1200494145) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L15)):*
Имеет смысл сделать ссылку на перевод раздела о FFI

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 30 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT4kM87tfCRIkTJAe3:-KFT4kM87tfCRIkTJAe4:1418922571) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L30)):*
функцию ioctl и передать туда структуру ifreq.

Далее тоже нужно поправить порядок слов в ситуациях "существительное + название" - сначала что это, затем название.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 98 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT5Y9QTPvCJqCSiiwJ:-KFT5Y9QTPvCJqCSiiwK:895371169) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L98)):*
в тип языка Си sockaddr.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 232 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT6TPcpPAGTjF9BkVl:-KFT6TPd1dk_rAY2Si7x:-227889149) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L232)):*
размером

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101)*

**Comment by DarkEld3r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 15 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT4QPL58r008ub-fH_:-KFcotYrZREytFurS5Er:-499146009) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L15)):*
Done.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 30 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT4kM87tfCRIkTJAe3:-KFcpRgwLQV49bHjqZeV:-499146009) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L30)):*
Done.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 98 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT5Y9QTPvCJqCSiiwJ:-KFcos4FgTAR5tPQL_gp:-499146009) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L98)):*
Done.

---

*[_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md, line 232 \[r1\]](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-KFT6TPcpPAGTjF9BkVl:-KFcol5eHDan5HBU9vpw:-499146009) ([raw file](https://github.com/rurust/rustycrate.ru/blob/0ea3d2da39b7d3e89fde31ffbd5b4d03edad05c4/_posts/2016-04-13-working-with-c-unions-in-rust-ffi.md#L232)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101)*

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101)*

**Comment by mkpankov** [comment]
:+1:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/rustycrate.ru/101#-:-KFdRZPA4y3PpXm7ORiW:676269983)*

**Pull request merged**
