### PR TITLE
Gemfile: Add json gem to fix jekyll launch issue

### PR DESCRIPTION
**Pull request by JIghtuse**
Without 'json' gem on Fedora 23 you got this:

    $ bundle exec jekyll serve
      Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- json' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
    /home/user/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:56:in `rescue in block in gracefully_require': jekyll-coffeescript (Jekyll::Errors::MissingDependencyException)
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:45:in `block in gracefully_require'
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:44:in `each'
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll/deprecator.rb:44:in `gracefully_require'
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/lib/jekyll.rb:141:in `<top (required)>'
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/bin/jekyll:6:in `require'
            from /home/user/.gem/ruby/gems/jekyll-2.4.0/bin/jekyll:6:in `<top (required)>'
            from /home/user/bin/jekyll:23:in `load'
            from /home/user/bin/jekyll:23:in `<main>'

[Review on Reviewable](https://reviewable.io/reviews/rurust/rustycrate.ru/76)

### CODE REVIEW

**Comment by mkpankov** [comment]
Как говорит ошибка на Travis, нужно обновить `Gemfile.lock`. Для этого локально сделай `bundle install` - `Gemfile.lock` должен измениться. Закоммить его и обнови PR.

**Comment by JIghtuse** [comment]
@mkpankov кажется, новые проблемы уже не мои

**Comment by mkpankov** [comment]
@JIghtuse не твои :) `htmlproof` много проблем что-то вызывает.

**Comment by mkpankov** [comment]
Сделай пожалуйста rebase, я сделал чтобы тот URL игнорировался - сборка должна пройти

**Comment by mkpankov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rurust/rustycrate.ru/76)*

**Pull request merged**
